[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 5180
  port = 8888
  autoLaunch = false
  framework = "vite"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."ocr"]
  timeout = 26

[functions."ocr-status"]
  timeout = 26
